// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-axios";
import type {
  GetRomsRomsGetError,
  GetRomsRomsGetResponse,
  GetRoomsRoomsGetError,
  GetRoomsRoomsGetResponse,
  CreateRoomRoomsPostData,
  CreateRoomRoomsPostError,
  CreateRoomRoomsPostResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Get Roms
 */
export const getRomsRomsGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRomsRomsGetResponse,
    GetRomsRomsGetError,
    ThrowOnError
  >({
    ...options,
    url: "/roms",
  });
};

/**
 * Get Rooms
 */
export const getRoomsRoomsGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRoomsRoomsGetResponse,
    GetRoomsRoomsGetError,
    ThrowOnError
  >({
    ...options,
    url: "/rooms",
  });
};

/**
 * Create Room
 */
export const createRoomRoomsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoomRoomsPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRoomRoomsPostResponse,
    CreateRoomRoomsPostError,
    ThrowOnError
  >({
    ...options,
    url: "/rooms",
  });
};
