// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type Rom = {
  id: string;
  art: string;
  title: string;
};

export type RoomCreate = {
  rom_id: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetRomsRomsGetResponse = Array<Rom>;

export type GetRomsRomsGetError = unknown;

export type GetRoomsRoomsGetResponse = Array<number>;

export type GetRoomsRoomsGetError = unknown;

export type CreateRoomRoomsPostData = {
  body: RoomCreate;
};

export type CreateRoomRoomsPostResponse = number;

export type CreateRoomRoomsPostError = HTTPValidationError;
