// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type PlayerPublic = {
  id?: number;
  nick: string;
};

export type Rom = {
  id: string;
  art: string;
  title: string;
  author: string;
  link: string;
};

export type RoomCreate = {
  rom_id: string;
};

export type RoomPublic = {
  id: number;
  players: Array<PlayerPublic>;
  rom: Rom;
  started_at: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetRomsRomsGetResponse = Array<Rom>;

export type GetRomsRomsGetError = unknown;

export type GetRoomsRoomsGetResponse = Array<RoomPublic>;

export type GetRoomsRoomsGetError = unknown;

export type CreateRoomRoomsPostData = {
  body: RoomCreate;
};

export type CreateRoomRoomsPostResponse = number;

export type CreateRoomRoomsPostError = HTTPValidationError;
