[tool.pyright]
include = ["src", "."]
venvPath = "."
venv = ".venv"

[virtualenvs]
in-project = true

[project]
name = "app"
version = "0.1.0"
description = "Project for HackTX 2024"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "sqlmodel>=0.0.22",
]
