/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateroomImport } from './routes/createroom'
import { Route as IndexImport } from './routes/index'
import { Route as RoomsIndexImport } from './routes/rooms.index'
import { Route as RoomsRoomIdImport } from './routes/rooms.$roomId'

// Create/Update Routes

const CreateroomRoute = CreateroomImport.update({
  id: '/createroom',
  path: '/createroom',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsIndexRoute = RoomsIndexImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsRoomIdRoute = RoomsRoomIdImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/createroom': {
      id: '/createroom'
      path: '/createroom'
      fullPath: '/createroom'
      preLoaderRoute: typeof CreateroomImport
      parentRoute: typeof rootRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdImport
      parentRoute: typeof rootRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createroom': typeof CreateroomRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms': typeof RoomsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createroom': typeof CreateroomRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms': typeof RoomsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/createroom': typeof CreateroomRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/': typeof RoomsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createroom' | '/rooms/$roomId' | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createroom' | '/rooms/$roomId' | '/rooms'
  id: '__root__' | '/' | '/createroom' | '/rooms/$roomId' | '/rooms/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateroomRoute: typeof CreateroomRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateroomRoute: CreateroomRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/createroom",
        "/rooms/$roomId",
        "/rooms/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/createroom": {
      "filePath": "createroom.tsx"
    },
    "/rooms/$roomId": {
      "filePath": "rooms.$roomId.tsx"
    },
    "/rooms/": {
      "filePath": "rooms.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
